package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelo.Servico;
import DAO.ServicoDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author layll
 */
public class TelaServico extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaServico.class.getName());
     
      private final DefaultTableModel modelo;
      
      
      private javax.swing.JFrame telaAnterior;
    /**
     * Creates new form TelaServiço
     */
    public TelaServico() {
        initComponents();
        
        txtID.setEditable(false);
         modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                carregarDadosTabela();
            }
        });
        
       atualizarTabela(); 
        
    }

    public TelaServico(javax.swing.JFrame telaAnterior) {
        this(); 
        this.telaAnterior = telaAnterior; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        labelDadosServico = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelNomeServico = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelListaServicos = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNomeServico = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serviços (Cadastro/Consulta)");

        btnNovo.setBackground(new java.awt.Color(102, 0, 153));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnSalvar.setBackground(new java.awt.Color(102, 0, 153));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnAlterar.setBackground(new java.awt.Color(102, 0, 153));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(102, 0, 153));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(102, 0, 153));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnVoltar.setBackground(new java.awt.Color(102, 0, 153));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        labelDadosServico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDadosServico.setForeground(new java.awt.Color(102, 0, 153));
        labelDadosServico.setText("Dados do Serviço");

        labelID.setText("ID:");

        labelNomeServico.setText("Nome do Serviço:");

        labelValor.setText("Valor (R$):");

        labelListaServicos.setBackground(new java.awt.Color(255, 255, 255));
        labelListaServicos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelListaServicos.setForeground(new java.awt.Color(102, 0, 153));
        labelListaServicos.setText("Lista de Serviços");

        txtID.addActionListener(this::txtIDActionPerformed);

        txtNomeServico.addActionListener(this::txtNomeServicoActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Serviço", "Valor (R$)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(24, 24, 24)
                        .addComponent(btnSalvar)
                        .addGap(26, 26, 26)
                        .addComponent(btnAlterar)
                        .addGap(29, 29, 29)
                        .addComponent(btnExcluir)
                        .addGap(27, 27, 27)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDadosServico, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelListaServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelValor))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addGap(18, 18, 18)
                .addComponent(labelDadosServico)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeServico)
                    .addComponent(txtNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(labelListaServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um serviço!");
            return;
        }

        try {
            
            long id = Long.parseLong(modelo.getValueAt(linha, 0).toString());

            
            Servico servico = new Servico();
            servico.setId(id);
            servico.setNome(txtNomeServico.getText().trim());
            servico.setValor(txtValor.getText().trim());

            
            ServicoDAO dao = new ServicoDAO();
            dao.atualizar(servico);

            
            modelo.setValueAt(servico.getNome(), linha, 1);
            modelo.setValueAt(servico.getValor(), linha, 2);

            JOptionPane.showMessageDialog(this, "Serviço alterado com sucesso!");

            limparCampos();
            jTable1.clearSelection();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar no banco: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
          limparCampos();
        jTable1.clearSelection();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // não precisa de codigo, pois é ID.
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNomeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeServicoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
      
if (txtNomeServico.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do serviço!");
            return;
        }

        if (txtValor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o valor!");
            return;
        }

        try {
            Servico servico = new Servico();
            
            servico.setNome(txtNomeServico.getText().trim());
            servico.setValor(txtValor.getText().trim());

            ServicoDAO dao = new ServicoDAO();
            dao.inserir(servico);

            JOptionPane.showMessageDialog(this, "Serviço salvo com sucesso!");
            limparCampos();
            
            
            atualizarTabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar no banco: " + e.getMessage());
        }

          
    

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         
        int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um serviço!");
            return;
        }

        int resp = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (resp == JOptionPane.YES_OPTION) {
            try {
                
                long id = Long.parseLong(modelo.getValueAt(linha, 0).toString());

                
                ServicoDAO dao = new ServicoDAO();
                dao.excluir(id);

                
                modelo.removeRow(linha);
                limparCampos();
                jTable1.clearSelection();
                
                JOptionPane.showMessageDialog(this, "Serviço excluído com sucesso!");

                atualizarTabela();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir no banco: " + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       
        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true); // Faz a tela que chamou (Admin ou Recep) reaparecer
            this.dispose();                     // Fecha a tela de serviço
        }
        
    }//GEN-LAST:event_btnVoltarActionPerformed
    private void carregarDadosTabela() {

        int linha = jTable1.getSelectedRow();

        if (linha != -1) {
            txtID.setText(modelo.getValueAt(linha, 0).toString());
            txtNomeServico.setText(modelo.getValueAt(linha, 1).toString());
            txtValor.setText(modelo.getValueAt(linha, 2).toString());
        }
    }
    private void limparCampos() {
        txtID.setText("");
        txtNomeServico.setText("");
        txtValor.setText("");
        txtNomeServico.requestFocus();
    }
    
    private void atualizarTabela() {
        modelo.setRowCount(0); 
        try {
            ServicoDAO dao = new ServicoDAO();
           
            for (Servico servico : dao.listar()) {
                modelo.addRow(new Object[]{
                    servico.getId(),
                    servico.getNome(),
                    servico.getValor()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar serviços: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaServico().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDadosServico;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelListaServicos;
    private javax.swing.JLabel labelNomeServico;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNomeServico;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
