/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.ProdutoVendaDAO;
import Modelo.ProdutoVenda;

/**
 *
 * @author Java
 */
public class TelaProdutoVenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaProdutoVenda.class.getName());
       private final DefaultTableModel modelo;
      
   private javax.swing.JFrame telaAnterior;
       
       //essa e a parte do CONSTRUTOR.
    public TelaProdutoVenda() {
        initComponents();
        txtCodigo.setEditable(false);
        
        modelo = (DefaultTableModel) jTable1.getModel();
        
        
        preencherTabela();
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
        carregarDadosTabela();
    }
});
    }
    
    public TelaProdutoVenda(javax.swing.JFrame telaAnterior) {
        this(); 
        this.telaAnterior = telaAnterior; 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDadosVenda = new javax.swing.JLabel();
        labelProdutosVenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtValorVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValorCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos de Venda");
        setResizable(false);

        labelDadosVenda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDadosVenda.setForeground(new java.awt.Color(102, 0, 153));
        labelDadosVenda.setText("Dados do Produto");

        labelProdutosVenda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelProdutosVenda.setForeground(new java.awt.Color(102, 0, 153));
        labelProdutosVenda.setText("Lista de Produtos de Venda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Produto", "Compra (R$)", "Venda (R$)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Valor de Venda (R$):");

        txtValorVenda.addActionListener(this::txtValorVendaActionPerformed);

        jLabel2.setText("Valor de Compra (R$): ");

        txtValorCompra.addActionListener(this::txtValorCompraActionPerformed);

        jLabel3.setText("Nome do Produto:");

        txtNomeProduto.addActionListener(this::txtNomeProdutoActionPerformed);

        jLabel4.setText("Codigo:");

        btnNovo.setBackground(new java.awt.Color(102, 0, 153));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(this::btnNovoActionPerformed);

        btnSalvar.setBackground(new java.awt.Color(102, 0, 153));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnAlterar.setBackground(new java.awt.Color(102, 0, 153));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(102, 0, 153));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(102, 0, 153));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnVoltar.setBackground(new java.awt.Color(102, 0, 153));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProdutosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDadosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)))
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addGap(18, 18, 18)
                .addComponent(labelDadosVenda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(labelProdutosVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVendaActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limparCampos();
    jTable1.clearSelection();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed
   
    private void limparCampos() {
    txtCodigo.setText("");
    txtNomeProduto.setText("");
    txtValorCompra.setText("");
    txtValorVenda.setText("");
    txtNomeProduto.requestFocus();
    
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
                                                   
    
    if (txtNomeProduto.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o nome do produto!");
        return;
    }
    if (txtValorCompra.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o valor de compra!");
        return;
    }
    if (txtValorVenda.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o valor de venda!");
        return;
    }
   
    if (!validarValores()){  
        return;
    }

   
    try {
        ProdutoVenda ProdutoVenda = new ProdutoVenda();
        
        
        
        ProdutoVenda.setNome(txtNomeProduto.getText().trim());        
    ProdutoVenda.setValorcompra(txtValorCompra.getText().trim());
    ProdutoVenda.setValorvenda(txtValorVenda.getText().trim());

        ProdutoVendaDAO dao = new ProdutoVendaDAO();
        dao.inserir(ProdutoVenda); 
 

        JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!");
        limparCampos();
        
        preencherTabela();

    } catch (Exception e) {
        
        JOptionPane.showMessageDialog(this, "Erro ao salvar no banco: " + e.getMessage());
    }
}                                         

private boolean validarValores() {
    try {
        Double.valueOf(txtValorCompra.getText().replace(",", "."));
        Double.valueOf(txtValorVenda.getText().replace(",", "."));
        return true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Informe valores numéricos válidos!");
        return false;
    }
   
    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
          
int linha = jTable1.getSelectedRow();

    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um produto!");
        return;
    }
  
    if (txtNomeProduto.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o nome do produto!");
        return;
    }
  
    if (txtValorCompra.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Informe o valor de compra!");
        return;
    }
    
    if (txtValorVenda.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o valor de venda!");
        return;
    
    }
    
    if (!validarValores()){
        return;
    }
    
    
    try {
       
        String codigoString = modelo.getValueAt(linha, 0).toString();
        long codigo = Long.parseLong(codigoString);

       
        ProdutoVenda produtoVenda = new ProdutoVenda();
        produtoVenda.setCodigoProduto(codigo); 
        produtoVenda.setNome(txtNomeProduto.getText().trim());
        produtoVenda.setValorcompra(txtValorCompra.getText().trim());
        produtoVenda.setValorvenda(txtValorVenda.getText().trim());

        ProdutoVendaDAO dao = new ProdutoVendaDAO();
        dao.atualizar(produtoVenda); 

       
        modelo.setValueAt(txtNomeProduto.getText().trim(), linha, 1);
        modelo.setValueAt(txtValorCompra.getText().trim(), linha, 2);
        modelo.setValueAt(txtValorVenda.getText().trim(), linha, 3);

        JOptionPane.showMessageDialog(this, "Produto alterado com sucesso no banco e na tela!");
        
        limparCampos();
        jTable1.clearSelection();

    } catch (Exception e) {
        
        JOptionPane.showMessageDialog(this, "Erro ao alterar no banco: " + e.getMessage());
    }
    
    
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
           
int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto!");
            return;
        }

        int resp = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (resp == JOptionPane.YES_OPTION) {
            try {
                
                String codigoString = modelo.getValueAt(linha, 0).toString();
                long codigo = Long.parseLong(codigoString);

              
                ProdutoVendaDAO dao = new ProdutoVendaDAO();
                dao.excluir(codigo); 

                
                limparCampos();

                
                preencherTabela();

                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso do banco e da tela!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir no banco: " + e.getMessage());
            }
        }
       
    
        
    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
          if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true); 
            this.dispose();                     
        }

    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtValorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompraActionPerformed
  
    private void carregarDadosTabela() {
    int linha = jTable1.getSelectedRow();

    if (linha != -1) {
        txtCodigo.setText(modelo.getValueAt(linha, 0).toString());
        txtNomeProduto.setText(modelo.getValueAt(linha, 1).toString());
        txtValorCompra.setText(modelo.getValueAt(linha, 2).toString());
        txtValorVenda.setText(modelo.getValueAt(linha, 3).toString());
    }
    
    }
    
    
    private void preencherTabela() {
        ProdutoVendaDAO dao = new ProdutoVendaDAO();
        java.util.List<ProdutoVenda> lista = dao.listar();
        
        modelo.setNumRows(0); 
        
        for (ProdutoVenda p : lista) {
            modelo.addRow(new Object[]{
                p.getCodigoProduto(),
                p.getNome(),
                p.getValorcompra(),
                p.getValorvenda()
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaProdutoVenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDadosVenda;
    private javax.swing.JLabel labelProdutosVenda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtValorCompra;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
